### ISSUE TITLE
Yarn docs error

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/website#114]
When I run `yarn install && yarn docs` I get this error:

```console
→ yarn docs
yarn run v1.7.0
$ npm run clean && npm run generate-docs

> website@1.0.0 clean /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> npm run rm-languages && npm run rm-beautifiers && npm run rm-options && npm run rm-executables


> website@1.0.0 rm-languages /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> rimraf 'docs/language-*'


> website@1.0.0 rm-beautifiers /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> rimraf 'docs/beautifier-*'


> website@1.0.0 rm-options /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> rimraf 'docs/option-*' && rimraf 'docs/options-for-languages.md'


> website@1.0.0 rm-executables /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> rimraf 'docs/executable-*'


> website@1.0.0 generate-docs /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website
> ts-node scripts/generate-docs

brace_style - HTML - BAD EXAMPLES
newline_between_rules - CSS - BAD EXAMPLES
Error: Dependency "Black" is required and not installed.
  - spawn black ENOENT
  - spawn black ENOENT
  - spawn black ENOENT
    at loadVersion.then.catch.then.isInstalled (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/node_modules/unibeautify/src/DependencyManager/Dependency.ts:34:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@1.0.0 generate-docs: `ts-node scripts/generate-docs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website@1.0.0 generate-docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marvinheilemann/.npm/_logs/2018-07-05T09_35_41_495Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Node: v10.4.1
Yarn: 1.7.0
on latest OSX (10.13.5)

> that results in empty .md doc files (beautifier-black-beautifier.md etc.).

A resulting error is that when I do `cd website/ && yarn start` and navigate to `http://localhost:3000/docs/about.html` that I get this browser error:

```
Error: Improper sidebars.json file, document with id 'beautifier-black' not found. Make sure that documents with the ids specified in sidebars.json exist and that no ids are repeated.
    at _loop (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/docusaurus/lib/server/readCategories.js:58:17)
    at readCategories (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/docusaurus/lib/server/readCategories.js:34:53)
    at DocsSidebar.render (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/docusaurus/lib/core/DocsSidebar.js:18:26)
    at processChild (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
    at resolve (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
    at ReactDOMServerRenderer.render (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
    at ReactDOMServerRenderer.read (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
    at renderToStaticMarkup (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/react-dom/cjs/react-dom-server.node.development.js:2737:25)
    at renderToStaticMarkupWithDoctype (/Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/docusaurus/lib/server/renderUtils.js:16:30)
    at /Users/marvinheilemann/Documents/Projects/_plugins/Unibeautify/website/website/node_modules/docusaurus/lib/server/server.js:283:14
```

**Comment by Glavin001** [comment]
The error message says:

> Error: Dependency "Black" is required and not installed.

You need to install [Black](https://github.com/ambv/black).

I do agree, this should be documented better (PRs welcome!) however there supported beautifiers are listed in https://github.com/Unibeautify/website/blob/master/scripts/generate-docs/beautifiers.ts#L12-L22 and I would prefer not to manually keep the README in sync.

If you'd like to add documentation to the README, check out https://github.com/Unibeautify/vscode#books-support and https://github.com/Unibeautify/vscode/blob/master/scripts/update-readme.ts and https://github.com/Unibeautify/vscode/blob/master/package.json#L23

---

You can use Docker to build: https://github.com/Unibeautify/website#testing-netlify-with-docker
However, it does not yet have the ability to serve the website, only build. If you are familiar with Docker, feel free to edit.

**Comment by muuvmuuv** [comment]
Yep, now it works. There should be a line in README that says "Install Black: ..."

**Comment by Glavin001** [comment]
> There should be a line in README that says "Install Black: ..."

It's not just Black. It's every applicable executable for the supported beautifiers needs to be installed.
List of beautifiers: https://github.com/Unibeautify/website/blob/master/scripts/generate-docs/beautifiers.ts#L13-L21
List of executables needing to be installed: https://unibeautify.com/docs/executable-black-black.html
